In [5]:
# Custom libraries/external files
import src.dual_unitary as du
import numpy as np

#### Testing

Testing can be run with:

```
pytest du_circuits/test/du_test.py
```

while in the main folder. Or, to test an specific class in the test file, such as 'TestCircuit':

```
pytest du_circuits/test/du_test.py::TestCircuit
```

#### Running functions

In [7]:
du.dual_unitary_cphase(np.pi/4)

array([[0.70710678+0.70710678j, 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 1.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 1.        +0.j        ]])

In [9]:
du.permutator([1, 2, 3, 4, 5, 6, 7])

array([2, 4, 1, 6, 3, 7, 5])

In [10]:
du.circuit_eigenstate(np.pi/4, 0, [1, 1, 0, 0, 0])

array([0.4472136 +0.j        , 0.39847023+0.20303072j,
       0.44170765+0.06995962j, 0.3618034 +0.26286556j,
       0.4253254 +0.1381966j ])